name: test

on: [pull_request]
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_KEY: ${{ secrets.JWT_KEY }}
    steps:
      - name: Perfrom unit tests
        env:
          JWT_KEY: niranjan
        run: echo $JWT_KEY
